##################################################
#                                                #
# This is my makefile for CYBR 2250 Program 5    #
#                                                #
# File author: Elisabeth Henderson               #
# Date:        Friday December 8, 2017           #
#                                                #
##################################################

# To make the program for this assignment. It needs itself and function.s.
calc : calc.c function.s
	    gcc -Wall -pedantic -std=c1x -g -o calc calc.c function.s

# a "clean" option to get rid of all miscellaneous things when done.
clean :
	    -rm ./*.o ./calc


