##################################################
#                                                #
# This is my makefile for CYBR 2250 Program 1    #
#                                                #
# File author: Elisabeth Henderson               #
# Date:        Friday September 22, 2017         #
#                                                #
##################################################

# To make the program for this assignment. It only needs itself.
taxi : taxi.c
	gcc -Wall -pedantic -std=c1x -o taxi taxi.c

# a "clean" option to get rid of all miscellaneous things when done.
clean : 
	-rm ./*.o ./taxi
